# This is the config file for cast
# It is located at /etc/cast/config.toml

# Self explanatory, will curse and insult you if enabled
# default: false
insult = false

[modules]
# Enables experimental features, use at your own risk
# default: false
experimentals = false 
horizon = false