[project]
name = "cast"
version = "3.1.0"
description = "A swiss army knife for casting spells"
authors = [
    {name = "pupyrinth",email = "contact@pupyrinth.dev"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "typer (>=0.15.4,<0.16.0)",
  "tomli (>=2.2.1,<3.0.0)"
]
