# This is the config file for cast
# It is located at /home/USER/.config/cast/config.toml

# Set the epoch time for the age command, so it uses this instead of the systems or without
# having to use the flag each time
# example = 1742944940
# default = -1
epoch = -1

# Self explanatory, will curse and insult you if enabled
# default: false
insult = false

[modules]
# Enables experimental features, use at your own risk
# default: false
experimental = false
# Various fixes for different applications
# default: false
fixes = false
# Package manager commands
# default: false
packageManager = false

# 
# default: false
[modules.horizon]
enabled = false
# Commands for distrobox
# default: true
distrobox = true

# Just various commands I use
# default: false
[modules.umbra]
enabled = false
# Bitfocus Companion
# default: true
bfc = true
# Some commands that comebine some git commands
# default: true
git = true